[package]
name = "cortex-a9"
authors.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
bit_field = "0.10.2"
registers = { path = "../registers" }
zynq-pac = { path = "../zynq-pac" }

[features]
power_saving = []
default = ["power_saving"]
