[package]
name = "register-macro"
authors.workspace = true
version.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.92"
quote = "1.0.37"
syn = { version = "2.0.90", features = ["full", "extra-traits"] }
registers = { path = "../registers" }
