[build]
target = "zynq-target.json"

[target.zynq-target]
rustflags = "-C link-arg=-Tmemory.x"

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]
