[package]
name = "zynq-pac"
version = "0.1.0"
edition = "2021"

[dependencies]
registers = { path = "../registers" }
register-macro = { path = "../register_macro" }
volatile-register = "0.2.2"

[features]
uart = []
